services:
    sylius-webserver:
        container_name: 'WebgriffeSyliusAkeneoPlugin__Sylius-Store-Webserver'
        image: sylius/standard:1.11-traditional-alpine
        environment:
            APP_ENV: "dev"
            DATABASE_URL: "mysql://root:mysql@mysql/sylius_%kernel.environment%?charset=utf8mb4"
#            DATABASE_URL: "pgsql://root:postgres@postgres/sylius_%kernel.environment%?charset=utf8" # When using postgres
            PHP_DATE_TIMEZONE: "Europe/Warsaw"
        volumes:
            - ./:/app:delegated
            - ./.docker/sylius/php/php.ini:/etc/php8/php.ini:delegated
            - ./.docker/sylius/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
        ports:
            - 8080:80
        depends_on:
            - sylius-mysql-data
        networks:
            - sylius

    sylius-mysql-data:
        container_name: 'WebgriffeSyliusAkeneoPlugin__Sylius-Store-MySQL'
        image: mysql:8.0
        platform: linux/amd64
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        ports:
            - ${MYSQL_PORT:-3306}:3306
        volumes:
            - sylius-mysql-data:/var/lib/mysql:rw
        networks:
            - sylius

networks:
    sylius:
        driver: bridge

volumes:
    sylius-mysql-data:
