sylius_grid:
    templates:
        action:
            importProduct: '@WebgriffeSyliusAkeneoPlugin\Product\Grid\Action\import.html.twig'
    grids:
        sylius_admin_product:
            actions:
                item:
                    import:
                        type: importProduct
                        label: webgriffe_sylius_akeneo.ui.import
                        options:
                            link:
                                route: webgriffe_sylius_akeneo_product_import
                                parameters:
                                    productId: resource.id
                            icon: cloud download
                            color: violet

framework:
    messenger:
        routing:
            'Webgriffe\SyliusAkeneoPlugin\Message\ItemImport': main

