sylius_grid:
    templates:
        action:
            importProduct: '@WebgriffeSyliusAkeneoPlugin\Product\Grid\Action\import.html.twig'
    grids:
        sylius_admin_product:
            actions:
                item:
                    import:
                        type: importProduct
                        label: webgriffe_sylius_akeneo.ui.schedule_import
                        options:
                            link:
                                route: webgriffe_sylius_akeneo_product_import
                                parameters:
                                    productId: resource.id
                            icon: cloud download
                            color: violet
        webgriffe_sylius_akeneo_admin_item_import_result:
            driver:
                name: doctrine/orm
                options:
                    class: Webgriffe\SyliusAkeneoPlugin\Entity\ItemImportResult
            sorting:
                createdAt: desc
            fields:
                createdAt:
                    type: datetime
                    label: sylius.ui.created_at
                    sortable: ~
                akeneoEntity:
                    type: string
                    label: webgriffe_sylius_akeneo.ui.entity
                    sortable: ~
                akeneoIdentifier:
                    type: string
                    label: webgriffe_sylius_akeneo.ui.identifier
                    sortable: ~
                successful:
                    type: twig
                    label: webgriffe_sylius_akeneo.ui.successful
                    options:
                        template: '@WebgriffeSyliusAkeneoPlugin\ItemImportResult\Grid\Field\successful.html.twig'
                message:
                    type: string
                    label: webgriffe_sylius_akeneo.ui.message
            filters:
                createdAt:
                    type: date
                    label: sylius.ui.created_at
                akeneoEntity:
                    type: string
                    label: webgriffe_sylius_akeneo.ui.entity
                akeneoIdentifier:
                    type: string
                    label: webgriffe_sylius_akeneo.ui.identifier
                successful:
                    type: boolean
                    label: webgriffe_sylius_akeneo.ui.successful
                message:
                    type: string
                    label: webgriffe_sylius_akeneo.ui.message            

framework:
    messenger:
        routing:
            'Webgriffe\SyliusAkeneoPlugin\Message\ItemImport': main
        buses:
            sylius.command_bus:
                middleware:
                    # TODO we need to redefine validation and doctrine_transaction middleware because this config is not
                    #      merged with the one defined in
                    #      vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Resources/config/app/messenger.yaml
                    #      Maybe we can handle this in a DI extension.
                    - 'webgriffe_sylius_akeneo.middleware.item_import_result_logging'
                    - 'validation'
                    - 'doctrine_transaction'

monolog:
    channels: ['webgriffe_sylius_akeneo_plugin']
        
